# Generated by Django 3.1.13 on 2023-09-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_auto_20230926_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nationality',
            new_name='lebanese',
        ),
    ]
