# Generated by Django 3.1.13 on 2023-10-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_auto_20230926_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='lebanese',
        ),
    ]
